"""add created_at to poll table

Revision ID: 77b1ddd79d7c
Revises: 5ff3c97aed71
Create Date: 2026-01-30 17:52:27.837122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77b1ddd79d7c'
down_revision: Union[str, Sequence[str], None] = '5ff3c97aed71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polls', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('polls', 'created_at')
    # ### end Alembic commands ###
