"""Add voter_id column

Revision ID: a9b2007d640e
Revises: 99fb0cf2b2b8
Create Date: 2026-02-06 14:57:22.493338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9b2007d640e'
down_revision: Union[str, Sequence[str], None] = '99fb0cf2b2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('voter_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'voter_id')
    # ### end Alembic commands ###
