"""Add word_limit to questions

Revision ID: bc63d9f978ac
Revises: a9b2007d640e
Create Date: 2026-02-06 15:15:44.360083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc63d9f978ac'
down_revision: Union[str, Sequence[str], None] = 'a9b2007d640e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('word_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('questions', 'word_limit')
    # ### end Alembic commands ###
